/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ParameterSpaceService } from "../parameterSpace.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ParameterSpaceCreateInput } from "./ParameterSpaceCreateInput";
import { ParameterSpaceWhereInput } from "./ParameterSpaceWhereInput";
import { ParameterSpaceWhereUniqueInput } from "./ParameterSpaceWhereUniqueInput";
import { ParameterSpaceFindManyArgs } from "./ParameterSpaceFindManyArgs";
import { ParameterSpaceUpdateInput } from "./ParameterSpaceUpdateInput";
import { ParameterSpace } from "./ParameterSpace";
import { ExperimentFindManyArgs } from "../../experiment/base/ExperimentFindManyArgs";
import { Experiment } from "../../experiment/base/Experiment";
import { ExperimentWhereUniqueInput } from "../../experiment/base/ExperimentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ParameterSpaceControllerBase {
  constructor(
    protected readonly service: ParameterSpaceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ParameterSpace })
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ParameterSpaceCreateInput
  ): Promise<ParameterSpace> {
    return await this.service.create({
      data: data,
      select: {
        bounds: true,
        createdAt: true,
        id: true,
        name: true,
        parameterType: true,
        updatedAt: true,
        valueType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ParameterSpace] })
  @ApiNestedQuery(ParameterSpaceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<ParameterSpace[]> {
    const args = plainToClass(ParameterSpaceFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        bounds: true,
        createdAt: true,
        id: true,
        name: true,
        parameterType: true,
        updatedAt: true,
        valueType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ParameterSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ParameterSpaceWhereUniqueInput
  ): Promise<ParameterSpace | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        bounds: true,
        createdAt: true,
        id: true,
        name: true,
        parameterType: true,
        updatedAt: true,
        valueType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ParameterSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ParameterSpaceWhereUniqueInput,
    @common.Body() data: ParameterSpaceUpdateInput
  ): Promise<ParameterSpace | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          bounds: true,
          createdAt: true,
          id: true,
          name: true,
          parameterType: true,
          updatedAt: true,
          valueType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ParameterSpace })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ParameterSpaceWhereUniqueInput
  ): Promise<ParameterSpace | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          bounds: true,
          createdAt: true,
          id: true,
          name: true,
          parameterType: true,
          updatedAt: true,
          valueType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/experiments")
  @ApiNestedQuery(ExperimentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Experiment",
    action: "read",
    possession: "any",
  })
  async findManyExperiments(
    @common.Req() request: Request,
    @common.Param() params: ParameterSpaceWhereUniqueInput
  ): Promise<Experiment[]> {
    const query = plainToClass(ExperimentFindManyArgs, request.query);
    const results = await this.service.findExperiments(params.id, {
      ...query,
      select: {
        createdAt: true,
        goal: true,
        id: true,
        name: true,

        owner: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/experiments")
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "update",
    possession: "any",
  })
  async connectExperiments(
    @common.Param() params: ParameterSpaceWhereUniqueInput,
    @common.Body() body: ExperimentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiments: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/experiments")
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "update",
    possession: "any",
  })
  async updateExperiments(
    @common.Param() params: ParameterSpaceWhereUniqueInput,
    @common.Body() body: ExperimentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiments: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/experiments")
  @nestAccessControl.UseRoles({
    resource: "ParameterSpace",
    action: "update",
    possession: "any",
  })
  async disconnectExperiments(
    @common.Param() params: ParameterSpaceWhereUniqueInput,
    @common.Body() body: ExperimentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiments: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
